# This file was generated by GoReleaser. DO NOT EDIT.
cask "geol" do
  name "geol"
  desc "geol, the cli to efficiently display product end-of-life dates in your terminal using the endoflife.date API."
  homepage "https://github.com/opt-nc/geol"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "geol"
  manpage "manpages/geol.1.gz"
  bash_completion "completions/geol.bash"
  zsh_completion "completions/geol.zsh"
  fish_completion "completions/geol.fish"

  on_macos do
    on_intel do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "ee20cdad79c50e926981dce27fcf5c8af54eb00680291c804fb3c2f940aa4614"
    end
    on_arm do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "2c6246a3349ff904c1c3fcbc01aa9745e478487f1c811e141b24bd9ab1cfc152"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "281a694790fd54893ec47993b861580cff076a98961cbf4662b7aa87e2c0ed8a"
    end
    on_arm do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "ee54b4d011cc49d6cf33d9772c0c4566625e3bc58a966cfe7cc82ca9d401c91c"
    end
  end

  # No zap stanza required
end
