# This file was generated by GoReleaser. DO NOT EDIT.
cask "geol" do
  name "geol"
  desc "geol, the cli to efficiently display product end-of-life dates in your terminal using the endoflife.date API."
  homepage "https://github.com/opt-nc/geol"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "geol"
  manpage "manpages/geol.1.gz"
  bash_completion "completions/geol.bash"
  zsh_completion "completions/geol.zsh"
  fish_completion "completions/geol.fish"

  on_macos do
    on_intel do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "1fb0ef5567d655eed2432e53514b7853ea1d4dfbf04e666d41f2001b843a9136"
    end
    on_arm do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "cd02bb62a52f223b8d4c424f8652cf484dca8b43eba1ecd893c1e5487cfce278"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "20cd5c0b04f5c7c491a31a2a783398fae23248ce00e036099f50e79f378f1534"
    end
    on_arm do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "a500a2dd13c8bf1daa138d7636ba165ffd4549ee10db5cee5b10b39ac4318bc7"
    end
  end

  # No zap stanza required
end
