# This file was generated by GoReleaser. DO NOT EDIT.
cask "geol" do
  name "geol"
  desc "geol, CLI to efficiently show end-of-life dates for a number of products"
  homepage "https://github.com/opt-nc/geol"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "geol"
  bash_completion "completions/geol.bash"
  zsh_completion "completions/geol.zsh"
  fish_completion "completions/geol.fish"

  on_macos do
    on_intel do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "7a79d88d21b8fe6ea4a6c97bace4e6fdde0db576a3aa7b2f55cfb4d429a8875d"
    end
    on_arm do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "8a21a62dd76e32d2d478e5348143bfb5c6c61d179a4c43b198c03a3e7305d63b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "dc1aabf0a31918b02b5820be8ce332311b0265094c63e270b783e3c127131412"
    end
    on_arm do
      url "https://github.com/opt-nc/geol/releases/download/v#{version}/geol_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "ff951c7dc2f7efc6ff753426759cbe0ef757957fd7d9e74b9713f28a0f64984c"
    end
  end

  # No zap stanza required
end
