# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mobitag < Formula
  desc "mobitag-cli, le chemin le plus court entre le terminal et le sms."
  homepage "https://github.com/opt-nc/mobitag-cli"
  version "2.3.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opt-nc/mobitag-cli/releases/download/v2.3.0/mobitag_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "706e81709bd2bcbc6da08f7820c590db6e1f3122535356fc82c3a382c22322f9"

      def install
        bin.install "mobitag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opt-nc/mobitag-cli/releases/download/v2.3.0/mobitag_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c747f5035a07a9357d3ea35a655e56516ac521329d362f27c3fde1dfba2f513"

      def install
        bin.install "mobitag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/opt-nc/mobitag-cli/releases/download/v2.3.0/mobitag_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "195e9a7d7f39c07a5378d5179867ab69ad8c2063d004eb121ba1141e2fe4a812"
      def install
        bin.install "mobitag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opt-nc/mobitag-cli/releases/download/v2.3.0/mobitag_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "737f46d5134a14430f5bcd1fd61b8b887c744709b9447e86147ee9f3a46cd319"
      def install
        bin.install "mobitag"
      end
    end
  end
end
