# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mobitag < Formula
  desc "mobitag-cli, le chemin le plus court entre le terminal et le sms."
  homepage "https://github.com/opt-nc/mobitag-cli"
  version "1.2.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opt-nc/mobitag-cli/releases/download/v1.2.0/mobitag_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "30e3f02fdef8efc7b9468eb27e7159df80b9c699d75aec778a12ba4fbcbb52c4"

      def install
        bin.install "mobitag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opt-nc/mobitag-cli/releases/download/v1.2.0/mobitag_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "66619b6a28b98112d5ad3cae37e137123806c18fa989b6b153b2965a5fadc913"

      def install
        bin.install "mobitag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opt-nc/mobitag-cli/releases/download/v1.2.0/mobitag_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "72b1ce2457c727b056e6a9d627ee9cab4866db3064de721275433233efdd4561"

        def install
          bin.install "mobitag"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opt-nc/mobitag-cli/releases/download/v1.2.0/mobitag_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d957d4c64d223e0866b83bd5e7e71df3d16ec143e61e09cd0aab879d57e629ba"

        def install
          bin.install "mobitag"
        end
      end
    end
  end
end
